<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <Nullable>enable</Nullable>
        <LangVersion>default</LangVersion>
        <Company>StellarGames</Company>
        <Configurations>Debug;Release;Unity</Configurations>
        <Platforms>AnyCPU</Platforms>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\GameData\GameData.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Melanchall.DryWetMidi" Version="8.0.0" />
    </ItemGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Unity' ">
        <OutputPath>..\..\UnityProject\Assets\Plugins\</OutputPath>
    </PropertyGroup>
    
</Project>
