namespace GameData.Resources.Animation.Commands;

#if JSON_SERIALIZE
using System.Text.Json.Serialization;

[JsonDerivedType(typeof(TagCommand), nameof(TagCommand))]
[JsonDerivedType(typeof(SelectPaletteCommand), nameof(SelectPaletteCommand))]
[JsonDerivedType(typeof(LoadPaletteResourceCommand), nameof(LoadPaletteResourceCommand))]
[JsonDerivedType(typeof(SelectImageCommand), nameof(SelectImageCommand))]
[JsonDerivedType(typeof(LoadImageResourceCommand), nameof(LoadImageResourceCommand))]
[JsonDerivedType(typeof(LoadScreenResourceCommand), nameof(LoadScreenResourceCommand))]
[JsonDerivedType(typeof(DrawImageCommand), nameof(DrawImageCommand))]
[JsonDerivedType(typeof(StoreBackgroundCommand), nameof(StoreBackgroundCommand))]
[JsonDerivedType(typeof(FadeInCommand), nameof(FadeInCommand))]
[JsonDerivedType(typeof(NextFrameCommand), nameof(NextFrameCommand))]
[JsonDerivedType(typeof(StoreAreaCommand), nameof(StoreAreaCommand))]
[JsonDerivedType(typeof(FadeOutCommand), nameof(FadeOutCommand))]
[JsonDerivedType(typeof(ClearAreaCommand), nameof(ClearAreaCommand))]
[JsonDerivedType(typeof(LoadFontResourceCommand), nameof(LoadFontResourceCommand))]
[JsonDerivedType(typeof(SelectFontCommand), nameof(SelectFontCommand))]
[JsonDerivedType(typeof(UnknownCommand2012), nameof(UnknownCommand2012))]
[JsonDerivedType(typeof(UnknownCommand2002), nameof(UnknownCommand2002))]
[JsonDerivedType(typeof(UnknownCommand4214), nameof(UnknownCommand4214))]
[JsonDerivedType(typeof(UnknownCommandB606), nameof(UnknownCommandB606))]
[JsonDerivedType(typeof(UnknownCommandA601), nameof(UnknownCommandA601))]
[JsonDerivedType(typeof(UnknownCommand1121), nameof(UnknownCommand1121))]
[JsonDerivedType(typeof(UnknownCommand0110), nameof(UnknownCommand0110))]
[JsonDerivedType(typeof(UnknownCommandC051), nameof(UnknownCommandC051))]
[JsonDerivedType(typeof(UnknownCommandC031), nameof(UnknownCommandC031))]
[JsonDerivedType(typeof(LoadSoundResource), nameof(LoadSoundResource))]
[JsonDerivedType(typeof(UnknownCommand2312), nameof(UnknownCommand2312))]
[JsonDerivedType(typeof(UnknownCommand2322), nameof(UnknownCommand2322))]
[JsonDerivedType(typeof(UnknownCommandA014), nameof(UnknownCommandA014))]
[JsonDerivedType(typeof(UnknownCommandA0B5), nameof(UnknownCommandA0B5))]
[JsonDerivedType(typeof(UnknownCommandA534), nameof(UnknownCommandA534))]
[JsonDerivedType(typeof(UnknownCommand0500), nameof(UnknownCommand0500))]
[JsonDerivedType(typeof(UnknownCommand0510), nameof(UnknownCommand0510))]
[JsonDerivedType(typeof(UnknownCommandA516), nameof(UnknownCommandA516))]
[JsonDerivedType(typeof(UnknownCommandA536), nameof(UnknownCommandA536))]
[JsonDerivedType(typeof(UnknownCommandA524), nameof(UnknownCommandA524))]
[JsonDerivedType(typeof(UnknownCommand1021), nameof(UnknownCommand1021))]
[JsonDerivedType(typeof(UnknownCommand00C0), nameof(UnknownCommand00C0))]
[JsonDerivedType(typeof(UnknownCommand0080), nameof(UnknownCommand0080))]
[JsonDerivedType(typeof(UnknownCommandC041), nameof(UnknownCommandC041))]
[JsonDerivedType(typeof(UnknownCommand1101), nameof(UnknownCommand1101))]
[JsonDerivedType(typeof(UnknownCommand4004), nameof(UnknownCommand4004))]
[JsonDerivedType(typeof(DrawImageCommand2), nameof(DrawImageCommand2))]
[JsonDerivedType(typeof(UnknownCommandA094), nameof(UnknownCommandA094))]
[JsonDerivedType(typeof(UnknownCommand1201), nameof(UnknownCommand1201))]
[JsonDerivedType(typeof(UnknownCommand2302), nameof(UnknownCommand2302))]
[JsonDerivedType(typeof(UnknownCommand2402), nameof(UnknownCommand2402))]
[JsonDerivedType(typeof(UnknownCommand0400), nameof(UnknownCommand0400))]
[JsonDerivedType(typeof(UnknownCommandA5A7), nameof(UnknownCommandA5A7))]
[JsonDerivedType(typeof(UnknownCommandA526), nameof(UnknownCommandA526))]
[JsonDerivedType(typeof(UnknownCommandA514), nameof(UnknownCommandA514))]
[JsonDerivedType(typeof(UnknownCommandA114), nameof(UnknownCommandA114))]
[JsonDerivedType(typeof(UnknownCommandA034), nameof(UnknownCommandA034))]
[JsonDerivedType(typeof(UnknownCommandC061), nameof(UnknownCommandC061))]
[JsonDerivedType(typeof(UnknownCommand0070), nameof(UnknownCommand0070))]
#endif
public abstract class AnimatorCommand {
    public string Id { get; set; }
}