namespace GameData.Resources.Animation.Commands;

#if JSON_SERIALIZE
using System.Text.Json.Serialization;

[JsonDerivedType(typeof(TagFrame), nameof(TagFrame))]
[JsonDerivedType(typeof(SelectPaletteSlot), nameof(SelectPaletteSlot))]
[JsonDerivedType(typeof(LoadPaletteResource), nameof(LoadPaletteResource))]
[JsonDerivedType(typeof(SelectImageSlot), nameof(SelectImageSlot))]
[JsonDerivedType(typeof(LoadImageResource), nameof(LoadImageResource))]
[JsonDerivedType(typeof(LoadScreenResource), nameof(LoadScreenResource))]
[JsonDerivedType(typeof(DrawImage), nameof(DrawImage))]
[JsonDerivedType(typeof(StoreScreen), nameof(StoreScreen))]
[JsonDerivedType(typeof(FadeIn), nameof(FadeIn))]
[JsonDerivedType(typeof(NextFrame), nameof(NextFrame))]
[JsonDerivedType(typeof(StoreArea), nameof(StoreArea))]
[JsonDerivedType(typeof(FadeOut), nameof(FadeOut))]
[JsonDerivedType(typeof(ClearArea), nameof(ClearArea))]
[JsonDerivedType(typeof(LoadFontResource), nameof(LoadFontResource))]
[JsonDerivedType(typeof(SelectFontSlot), nameof(SelectFontSlot))]
[JsonDerivedType(typeof(DialogCommand), nameof(DialogCommand))]
[JsonDerivedType(typeof(SetColors), nameof(SetColors))]
[JsonDerivedType(typeof(CopyToCurrentBuffer), nameof(CopyToCurrentBuffer))]
[JsonDerivedType(typeof(CopyAreaBetweenBuffers), nameof(CopyAreaBetweenBuffers))]
[JsonDerivedType(typeof(DrawBuffer), nameof(DrawBuffer))]
[JsonDerivedType(typeof(SetActiveBuffer), nameof(SetActiveBuffer))]
[JsonDerivedType(typeof(UnknownCommand0110), nameof(UnknownCommand0110))]
[JsonDerivedType(typeof(PlaySound), nameof(PlaySound))]
[JsonDerivedType(typeof(LoadSound), nameof(LoadSound))]
[JsonDerivedType(typeof(LoadSoundResource), nameof(LoadSoundResource))]
[JsonDerivedType(typeof(SetRange2), nameof(SetRange2))]
[JsonDerivedType(typeof(SetRange3), nameof(SetRange3))]
[JsonDerivedType(typeof(UnknownCommandA014), nameof(UnknownCommandA014))]
[JsonDerivedType(typeof(UnknownCommandA0B5), nameof(UnknownCommandA0B5))]
[JsonDerivedType(typeof(UnknownCommandA534), nameof(UnknownCommandA534))]
[JsonDerivedType(typeof(UnknownCommand0500), nameof(UnknownCommand0500))]
[JsonDerivedType(typeof(UnknownCommand0510), nameof(UnknownCommand0510))]
[JsonDerivedType(typeof(UnknownCommandA516), nameof(UnknownCommandA516))]
[JsonDerivedType(typeof(UnknownCommandA536), nameof(UnknownCommandA536))]
[JsonDerivedType(typeof(UnknownCommandA524), nameof(UnknownCommandA524))]
[JsonDerivedType(typeof(SetDelay), nameof(SetDelay))]
[JsonDerivedType(typeof(UnknownCommand00C0), nameof(UnknownCommand00C0))]
[JsonDerivedType(typeof(DisposeCurrentBitmap), nameof(DisposeCurrentBitmap))]
[JsonDerivedType(typeof(StopSound), nameof(StopSound))]
[JsonDerivedType(typeof(UnknownCommand1101), nameof(UnknownCommand1101))]
[JsonDerivedType(typeof(SetClipArea), nameof(SetClipArea))]
[JsonDerivedType(typeof(DrawImageCommand2), nameof(DrawImageCommand2))]
[JsonDerivedType(typeof(UnknownCommandA094), nameof(UnknownCommandA094))]
[JsonDerivedType(typeof(GotoFrame), nameof(GotoFrame))]
[JsonDerivedType(typeof(SetRange1), nameof(SetRange1))]
[JsonDerivedType(typeof(UnknownCommand2402), nameof(UnknownCommand2402))]
[JsonDerivedType(typeof(UnknownCommand0400), nameof(UnknownCommand0400))]
[JsonDerivedType(typeof(UnknownCommandA5A7), nameof(UnknownCommandA5A7))]
[JsonDerivedType(typeof(UnknownCommandA526), nameof(UnknownCommandA526))]
[JsonDerivedType(typeof(UnknownCommandA514), nameof(UnknownCommandA514))]
[JsonDerivedType(typeof(UnknownCommandA114), nameof(UnknownCommandA114))]
[JsonDerivedType(typeof(UnknownCommandA034), nameof(UnknownCommandA034))]
[JsonDerivedType(typeof(UnknownCommandC061), nameof(UnknownCommandC061))]
[JsonDerivedType(typeof(DisposeCurrentPalette), nameof(DisposeCurrentPalette))]
#endif
public abstract class FrameCommand {
    public string Id { get; set; }
}